name: Template Sync

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.TEMPLATE_SYNC_PAT }}

      - name: Setup git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Run template sync
        id: sync
        uses: AndreasAugustin/actions-template-sync@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TEMPLATE_SYNC_PAT }}
        with:
          source_repo_path: swiss-ai-center/create-a-new-service-generic-template
          upstream_branch: main
          pr_labels: template-sync,automated-pr
          source_gh_token: ${{ secrets.TEMPLATE_SYNC_PAT }}

      - name: Change PR base to dev
        if: steps.sync.outputs.pr_number != ''
        env:
          GH_TOKEN: ${{ secrets.TEMPLATE_SYNC_PAT }}
        run: |
          gh pr edit ${{ steps.sync.outputs.pr_number }} --base dev